### PR TITLE
Add Sponsorship configuration

### PR DESCRIPTION
**Pull request by GSTVAC**

### CODE REVIEW

**Comment by huangqun** [comment]
@GSTVAC please submit to OR as well.

**Comment by GSTVAC** [comment]
@huangqun Done.

**Comment by huangqun** [comment]
This is still not full url, by full url I meant a url starting with http:// or https://, so that we can host the images on amazon s3 or dropbox or some other services and use them in arena. I tried https://www.dropbox.com/s/ktd2nemw0le9k4z/Olympic-logo.png and it didn't work

**Comment by GSTVAC** [comment]
@huangqun The URL above points to the dropbox page, not the image itself. You must use https://photos-3.dropbox.com/t/2/AACQDDC_cUOdJT0qnjLit48UFbretSkdfuROSv8TcEHdLw/12/767928/png/1024x768/3/1422882000/0/2/Olympic-logo.png/CLjvLiABIAIgAygBKAI/yaUdXlleEujQ6q3iQfm2fHMXpdO9Vvw1FBtnwaDzMlg.
I submitted a new merge request. #522

**Pull request closed without merging**
